Repository SWEET-DEVELOPERS/sweet-server, pull requests merged in 2024-01, with the labels that each got.

#6 [feat] 초기 엔티티 생성
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
  src/main/java/org/sopt/sweet/domain/gift/entity/Gift.java
  src/main/java/org/sopt/sweet/domain/gift/repository/GiftRepository.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
  src/main/java/org/sopt/sweet/domain/gifter/constant/TournamentDuration.java
  src/main/java/org/sopt/sweet/domain/gifter/controller/GifterController.java
  src/main/java/org/sopt/sweet/domain/gifter/entity/Gifter.java
  src/main/java/org/sopt/sweet/domain/gifter/entity/GifterMember.java
  src/main/java/org/sopt/sweet/domain/gifter/repository/GifterMemberRepository.java
  src/main/java/org/sopt/sweet/domain/gifter/repository/GifterRepository.java
  src/main/java/org/sopt/sweet/domain/gifter/service/GifterService.java
  src/main/java/org/sopt/sweet/domain/member/constant/SocialType.java
  src/main/java/org/sopt/sweet/domain/member/controller/MemberController.java
  src/main/java/org/sopt/sweet/domain/member/entity/Member.java
  src/main/java/org/sopt/sweet/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/sweet/domain/member/service/MemberService.java
  src/main/java/org/sopt/sweet/domain/product/controller/ProductController.java
  src/main/java/org/sopt/sweet/domain/product/entity/Product.java
  src/main/java/org/sopt/sweet/domain/product/repository/ProductRepository.java
  src/main/java/org/sopt/sweet/domain/product/service/ProductService.java
Labels: FEAT

#8 [feat] Swagger 연동
  build.gradle
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftApi.java
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
  src/main/java/org/sopt/sweet/domain/gifter/controller/GifterApi.java
  src/main/java/org/sopt/sweet/domain/gifter/controller/GifterController.java
  src/main/java/org/sopt/sweet/domain/member/controller/MemberApi.java
  src/main/java/org/sopt/sweet/domain/member/controller/MemberController.java
  src/main/java/org/sopt/sweet/domain/product/controller/ProductApi.java
  src/main/java/org/sopt/sweet/domain/product/controller/ProductController.java
  src/main/java/org/sopt/sweet/global/common/HealthCheckApiController.java
  src/main/java/org/sopt/sweet/global/config/SwaggerConfig.java
  src/main/java/org/sopt/sweet/global/config/auth/SecurityConfig.java
Labels: CHORE, FEAT

#10 [feat] 임시 로그인 API
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
  src/main/java/org/sopt/sweet/domain/gifter/controller/GifterController.java
  src/main/java/org/sopt/sweet/domain/member/controller/MemberApi.java
  src/main/java/org/sopt/sweet/domain/member/controller/MemberController.java
  src/main/java/org/sopt/sweet/domain/member/dto/request/MemberTokenResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/service/MemberService.java
  src/main/java/org/sopt/sweet/domain/product/controller/ProductController.java
  src/main/java/org/sopt/sweet/global/config/auth/SecurityConfig.java
Labels: FEAT

#13 [feat] 프론트 배포 주소 추가
  src/main/java/org/sopt/sweet/global/config/CorsConfig.java
Labels: FEAT

#17 [feat] OpenGraph 기능 구현
  build.gradle
  src/main/java/org/sopt/sweet/domain/opengraph/config/AppConfig.java
  src/main/java/org/sopt/sweet/domain/opengraph/controller/OpengraphController.java
  src/main/java/org/sopt/sweet/domain/opengraph/dto/OpengraphResponseDto.java
  src/main/java/org/sopt/sweet/domain/opengraph/dto/URLRequestDto.java
  src/main/java/org/sopt/sweet/domain/opengraph/lib/MetaElement.java
  src/main/java/org/sopt/sweet/domain/opengraph/lib/OpenGraph.java
  src/main/java/org/sopt/sweet/domain/opengraph/lib/OpenGraphNamespace.java
  src/main/java/org/sopt/sweet/domain/opengraph/service/OpengraphService.java
  src/main/java/org/sopt/sweet/global/config/auth/SecurityConfig.java
  src/main/java/org/sopt/sweet/global/error/ErrorCode.java
Labels: FEAT

#21 [refactor] 엔티티 이름 변경 및 리펙토링
  README.md
  src/main/java/org/sopt/sweet/domain/gift/entity/Gift.java
  src/main/java/org/sopt/sweet/domain/gifter/controller/GifterController.java
  src/main/java/org/sopt/sweet/domain/gifter/dto/request/PresignedURLRequestDto.java
  src/main/java/org/sopt/sweet/domain/gifter/dto/response/PresignedURLResponseDto.java
  src/main/java/org/sopt/sweet/domain/gifter/repository/GifterMemberRepository.java
  src/main/java/org/sopt/sweet/domain/gifter/repository/GifterRepository.java
  src/main/java/org/sopt/sweet/domain/gifter/service/GifterService.java
  src/main/java/org/sopt/sweet/domain/opengraph/controller/OpengraphAPI.java
  src/main/java/org/sopt/sweet/domain/opengraph/controller/OpengraphController.java
  src/main/java/org/sopt/sweet/domain/opengraph/service/OpengraphService.java
  src/main/java/org/sopt/sweet/domain/product/entity/Product.java
  src/main/java/org/sopt/sweet/domain/room/constant/TournamentDuration.java
  src/main/java/org/sopt/sweet/domain/room/controller/RoomApi.java
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/entity/Room.java
  src/main/java/org/sopt/sweet/domain/room/entity/RoomMember.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomMemberRepository.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomRepository.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
  src/main/java/org/sopt/sweet/domain/s3/controller/FileApi.java
  src/main/java/org/sopt/sweet/domain/s3/controller/FileController.java
  src/main/java/org/sopt/sweet/domain/s3/dto/request/PresignedUrlRequestDto.java
  src/main/java/org/sopt/sweet/domain/s3/dto/response/PresignedUrlResponseDto.java
  src/main/java/org/sopt/sweet/domain/s3/service/FileService.java
  src/main/java/org/sopt/sweet/global/external/opengraph/config/AppConfig.java
  src/main/java/org/sopt/sweet/global/external/opengraph/lib/MetaElement.java
  src/main/java/org/sopt/sweet/global/external/opengraph/lib/OpenGraph.java
  src/main/java/org/sopt/sweet/global/external/opengraph/lib/OpenGraphNamespace.java
  src/main/java/org/sopt/sweet/global/external/s3/config/FileConfig.java
  src/main/java/org/sopt/sweet/global/external/s3/config/S3Config.java
Labels: REFACTOR, RENAME

#22 [feat] 새로운 선물방 생성 기능 구현
  src/main/java/org/sopt/sweet/domain/room/controller/RoomApi.java
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/dto/request/CreateRoomRequestDto.java
  src/main/java/org/sopt/sweet/domain/room/entity/Room.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomRepository.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
  src/main/java/org/sopt/sweet/global/config/SwaggerConfig.java
  src/main/java/org/sopt/sweet/global/error/ErrorCode.java
Labels: FEAT

#24 [feat] 선물방 참여 관련 기능 구현
  src/main/java/org/sopt/sweet/domain/room/controller/RoomApi.java
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/dto/request/JoinRoomRequestDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/CreateRoomResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/JoinRoomResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomInviteResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/entity/Room.java
  src/main/java/org/sopt/sweet/domain/room/entity/RoomMember.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomMemberRepository.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
  src/main/java/org/sopt/sweet/global/config/auth/SecurityConfig.java
  src/main/java/org/sopt/sweet/global/error/ErrorCode.java
Labels: FEAT

#26 [feat] 선물 등록 관련 기능 구현
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftApi.java
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
  src/main/java/org/sopt/sweet/domain/gift/dto/request/CreateGiftRequestDto.java
  src/main/java/org/sopt/sweet/domain/gift/dto/request/MyGiftsRequestDto.java
  src/main/java/org/sopt/sweet/domain/gift/dto/response/MyGiftDto.java
  src/main/java/org/sopt/sweet/domain/gift/dto/response/MyGiftsResponseDto.java
  src/main/java/org/sopt/sweet/domain/gift/repository/GiftRepository.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
  src/main/java/org/sopt/sweet/global/error/ErrorCode.java
Labels: FEAT

#28 [feat] 선물방 정보 관련 기능 구현
  src/main/java/org/sopt/sweet/domain/gift/repository/GiftRepository.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
  src/main/java/org/sopt/sweet/domain/product/repository/ProductRepository.java
  src/main/java/org/sopt/sweet/domain/room/controller/RoomApi.java
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/HotProductGiftDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomDetailResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomFriendsGiftDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMainResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMyGiftDto.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
  src/main/java/org/sopt/sweet/global/error/ErrorCode.java
Labels: FEAT

#30 [feat] 선물방 정보 (이름, 썸네일) 수정 기능 구현
  src/main/java/org/sopt/sweet/domain/room/controller/RoomApi.java
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/dto/request/RoomImageRequestDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/request/RoomNameRequestDto.java
  src/main/java/org/sopt/sweet/domain/room/entity/Room.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
Labels: FEAT

#34 [feat] 선물방 멤버 관리 기능
  src/main/java/org/sopt/sweet/domain/room/controller/RoomApi.java
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMemberDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMembersResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomMemberRepository.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
  src/main/java/org/sopt/sweet/global/error/ErrorCode.java
Labels: FEAT

#31 [feat] 카카오 로그인 및 로그아웃 구현
  build.gradle
  src/main/java/org/sopt/sweet/domain/member/controller/MemberController.java
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthApi.java
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthController.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/KakaoUserInfoResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/MemberTokenResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/entity/Member.java
  src/main/java/org/sopt/sweet/domain/member/entity/OAuthToken.java
  src/main/java/org/sopt/sweet/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/sweet/domain/member/service/MemberService.java
  src/main/java/org/sopt/sweet/domain/member/service/OAuthService.java
  src/main/java/org/sopt/sweet/global/config/RedisConfig.java
  src/main/java/org/sopt/sweet/global/config/auth/SecurityConfig.java
Labels: FEAT

#36 [feat] 요즘 2030이 주목하는 선물 기능 구현
  build.gradle
  src/main/java/org/sopt/sweet/domain/product/controller/ProductApi.java
  src/main/java/org/sopt/sweet/domain/product/controller/ProductController.java
  src/main/java/org/sopt/sweet/domain/product/dto/response/HotProductDto.java
  src/main/java/org/sopt/sweet/domain/product/dto/response/HotProductsResponseDto.java
  src/main/java/org/sopt/sweet/domain/product/service/ProductService.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
Labels: FEAT

#39 [refactor] 토큰 만료 시간 변경
  src/main/java/org/sopt/sweet/domain/member/service/OAuthService.java
Labels: REFACTOR

#41 [fix] 로그인 API 코드 수정
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthApi.java
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthController.java
  src/main/java/org/sopt/sweet/domain/member/service/OAuthService.java
Labels: FIX

#45 [feat] #37 카카오 로그인 수정
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthController.java
Labels: FIX

#47 [feat] 선물 토너먼트 리스트 API 구현
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftApi.java
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
  src/main/java/org/sopt/sweet/domain/gift/dto/response/TournamentListsResponseDto.java
  src/main/java/org/sopt/sweet/domain/gift/repository/GiftRepository.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
Labels: FEAT

#52 [chore] 보안 취약점 발견으로 implementation 수정
  build.gradle
Labels: CHORE

#50 [feat] 선물 토너먼트 점수 입력 API & 토너먼트 정보 조회 API 구현
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftApi.java
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
  src/main/java/org/sopt/sweet/domain/gift/dto/request/TournamentScoreRequestDto.java
  src/main/java/org/sopt/sweet/domain/gift/dto/response/TournamentInfoDto.java
  src/main/java/org/sopt/sweet/domain/gift/entity/Gift.java
  src/main/java/org/sopt/sweet/domain/gift/repository/GiftRepository.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
  src/main/java/org/sopt/sweet/domain/room/entity/RoomMember.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomMemberRepository.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomRepository.java
Labels: FEAT

#53 [feat] 토너먼트 랭킹 조회
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftApi.java
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
  src/main/java/org/sopt/sweet/domain/gift/dto/response/TournamentRankingResponseDto.java
  src/main/java/org/sopt/sweet/domain/gift/repository/GiftRepository.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
Labels: FEAT

#55 [feat] 친구가 등록한 선물 조회 API 구현
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftApi.java
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
  src/main/java/org/sopt/sweet/domain/gift/dto/response/FriendGiftDto.java
  src/main/java/org/sopt/sweet/domain/gift/dto/response/TournamentStartDateResponseDto.java
  src/main/java/org/sopt/sweet/domain/gift/entity/Gift.java
  src/main/java/org/sopt/sweet/domain/gift/repository/GiftRepository.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
Labels: FEAT

#59 [fix] 2030 상품 API response에 토너먼트 시작 시간 추가
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
  src/main/java/org/sopt/sweet/domain/gift/entity/Gift.java
  src/main/java/org/sopt/sweet/domain/product/controller/ProductApi.java
  src/main/java/org/sopt/sweet/domain/product/controller/ProductController.java
  src/main/java/org/sopt/sweet/domain/product/dto/response/HotProductsResponseDto.java
  src/main/java/org/sopt/sweet/domain/product/service/ProductService.java
Labels: FEAT, FIX

#60 [feat] 종료된 선물방 API 구현
  src/main/java/org/sopt/sweet/domain/member/controller/MemberApi.java
  src/main/java/org/sopt/sweet/domain/member/controller/MemberController.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/ClosedRoomResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/service/MemberService.java
  src/main/java/org/sopt/sweet/domain/room/entity/Room.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomMemberRepository.java
Labels: FEAT

#62 [feat] 진행중인 선물방 API구현
  src/main/java/org/sopt/sweet/domain/member/controller/MemberApi.java
  src/main/java/org/sopt/sweet/domain/member/controller/MemberController.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/ActiveRoomResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/MemberInfoDto.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/MyPageResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/service/MemberService.java
  src/main/java/org/sopt/sweet/domain/room/entity/RoomMember.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomMemberRepository.java
Labels: FEAT

#65 [refactor] #64 불필요한 import, 중복되는 코드 제거
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftApi.java
  src/main/java/org/sopt/sweet/domain/gift/dto/response/FriendGiftDto.java
  src/main/java/org/sopt/sweet/domain/gift/dto/response/TournamentInfoDto.java
  src/main/java/org/sopt/sweet/domain/gift/dto/response/TournamentRankingResponseDto.java
  src/main/java/org/sopt/sweet/domain/gift/entity/Gift.java
  src/main/java/org/sopt/sweet/domain/gift/repository/GiftRepository.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
  src/main/java/org/sopt/sweet/domain/member/controller/MemberController.java
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthApi.java
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthController.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/ActiveRoomResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/ClosedRoomResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/KakaoUserInfoResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/entity/Member.java
  src/main/java/org/sopt/sweet/domain/member/service/MemberService.java
  src/main/java/org/sopt/sweet/domain/member/service/OAuthService.java
  src/main/java/org/sopt/sweet/domain/opengraph/controller/OpengraphController.java
  src/main/java/org/sopt/sweet/domain/opengraph/dto/OpengraphResponseDto.java
  src/main/java/org/sopt/sweet/domain/opengraph/service/OpengraphService.java
  src/main/java/org/sopt/sweet/domain/product/dto/response/HotProductsResponseDto.java
  src/main/java/org/sopt/sweet/domain/product/entity/Product.java
  src/main/java/org/sopt/sweet/domain/product/service/ProductService.java
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/CreateRoomResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/HotProductGiftDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomDetailResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomInviteResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMainResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMemberDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMembersResponseDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMyGiftDto.java
  src/main/java/org/sopt/sweet/domain/room/entity/Room.java
  src/main/java/org/sopt/sweet/domain/room/entity/RoomMember.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomMemberRepository.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomRepository.java
  src/main/java/org/sopt/sweet/domain/s3/dto/response/PresignedUrlResponseDto.java
  src/main/java/org/sopt/sweet/global/common/BaseTimeEntity.java
  src/main/java/org/sopt/sweet/global/common/HealthCheckApiController.java
  src/main/java/org/sopt/sweet/global/common/SuccessCode.java
  src/main/java/org/sopt/sweet/global/common/SuccessResponse.java
  src/main/java/org/sopt/sweet/global/config/CorsConfig.java
  src/main/java/org/sopt/sweet/global/config/JpaConfig.java
  src/main/java/org/sopt/sweet/global/config/RedisConfig.java
  src/main/java/org/sopt/sweet/global/config/SwaggerConfig.java
  src/main/java/org/sopt/sweet/global/config/WebConfig.java
  src/main/java/org/sopt/sweet/global/config/auth/ExceptionHandlerFilter.java
  src/main/java/org/sopt/sweet/global/config/auth/UserId.java
  src/main/java/org/sopt/sweet/global/config/auth/UserIdArgumentResolver.java
  src/main/java/org/sopt/sweet/global/error/dto/ErrorResponse.java
  src/main/java/org/sopt/sweet/global/error/exception/ConflictException.java
  src/main/java/org/sopt/sweet/global/error/exception/EntityNotFoundException.java
  src/main/java/org/sopt/sweet/global/error/exception/ForbiddenException.java
  src/main/java/org/sopt/sweet/global/error/exception/InternalServerException.java
  src/main/java/org/sopt/sweet/global/error/exception/InvalidValueException.java
  src/main/java/org/sopt/sweet/global/error/exception/UnauthorizedException.java
  src/main/java/org/sopt/sweet/global/external/s3/config/S3Config.java
Labels: REFACTOR, REMOVE

#66 [fix] 로그아웃 API 수정 및 토큰 재발급 API 구현
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthApi.java
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthController.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/MemberReissueTokenResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/service/OAuthService.java
  src/main/java/org/sopt/sweet/global/config/auth/SecurityConfig.java
  src/main/java/org/sopt/sweet/global/config/auth/jwt/JwtProvider.java
Labels: FEAT

#68 [refactor] 마이페이지 API BaseResponse 적용
  src/main/java/org/sopt/sweet/domain/member/controller/MemberApi.java
  src/main/java/org/sopt/sweet/domain/member/controller/MemberController.java
Labels: FEAT

#70 [fix] 친구들이 등록한 선물 조회 API response 수정
  src/main/java/org/sopt/sweet/domain/gift/dto/response/FriendGiftDto.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
Labels: FIX

#72 [fix] 내 선물 조회하기 API 엔드포인트 변경 및 종료된 선물방 response 추가
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftApi.java
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
  src/main/java/org/sopt/sweet/domain/member/dto/response/ClosedRoomResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/service/MemberService.java
Labels: FEAT

#73 [fix] 엔드포인트 수정
  src/main/java/org/sopt/sweet/domain/gift/controller/GiftController.java
Labels: FIX

#75 [fix] presigned Url API request 방식을 RequestParam으로 변경
  src/main/java/org/sopt/sweet/domain/s3/controller/FileApi.java
  src/main/java/org/sopt/sweet/domain/s3/controller/FileController.java
  src/main/java/org/sopt/sweet/domain/s3/service/FileService.java
Labels: FIX, REFACTOR

#76 [fix] request 방식을 RequestParam 변경에 따른 스웨거 코드 수정
  src/main/java/org/sopt/sweet/domain/s3/controller/FileApi.java
Labels: FIX, REFACTOR

#78 [fix] 선물방 참여자 상세 조회 수정
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/OwnerDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMemberDetailDto.java
  src/main/java/org/sopt/sweet/domain/room/repository/RoomMemberRepository.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
Labels: FIX

#80 [fix] 선물방 이미지 default값 추가
  src/main/java/org/sopt/sweet/domain/room/entity/Room.java
Labels: FIX

#82 [refactor] 토너먼트 점수 입력 request 변경
  src/main/java/org/sopt/sweet/domain/gift/dto/request/TournamentScoreRequestDto.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
Labels: REFACTOR

#83 [fix] 선물방 이미지 default값 설정 코드 수정
  src/main/java/org/sopt/sweet/domain/room/entity/Room.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
Labels: FIX

#87 [fix] 선물방 생성 기본 이미지 추가
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
Labels: FIX

#89 [fix] 초대코드 참여 API request RequestParam으로 변경
  src/main/java/org/sopt/sweet/domain/room/controller/RoomApi.java
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/dto/request/JoinRoomRequestDto.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
Labels: FIX, REFACTOR

#91 [fix] 토큰 재발급 API response에 리프레쉬 토큰 추가
  src/main/java/org/sopt/sweet/domain/member/dto/response/MemberReissueTokenResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/service/OAuthService.java
Labels: FIX

#93 [fix] 진행중인 선물방 조회 API response에 해당 멤버의 토너먼트 참여 여부 추가
  src/main/java/org/sopt/sweet/domain/member/dto/response/ActiveRoomResponseDto.java
  src/main/java/org/sopt/sweet/domain/member/service/MemberService.java
Labels: FIX

#95 [fix] 선물방 참여자 상세 조회 API 로직 분리
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMemberDetailDto.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomOwnerDetailDto.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
Labels: FEAT, FIX

#97 [refactor] 선물방 참여자 상세 조회 API response 요청에 따라 수정
  src/main/java/org/sopt/sweet/domain/room/controller/RoomController.java
  src/main/java/org/sopt/sweet/domain/room/dto/response/RoomMemberDto.java
  src/main/java/org/sopt/sweet/domain/room/service/RoomService.java
Labels: REFACTOR

#101 [fix]토큰 재발급 resposne에 리프레쉬 토큰 추가
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthApi.java
  src/main/java/org/sopt/sweet/domain/member/controller/OAuthController.java
  src/main/java/org/sopt/sweet/domain/member/service/OAuthService.java
Labels: FIX

#106 [fix] 진행중, 종료 선물방 분류 기준 변경
  src/main/java/org/sopt/sweet/domain/gift/dto/response/TournamentInfoDto.java
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
  src/main/java/org/sopt/sweet/domain/member/service/MemberService.java
Labels: FIX

#108 [fix] 선물 등록시 기본 이미지 추가
  src/main/java/org/sopt/sweet/domain/gift/service/GiftService.java
Labels: FIX, REFACTOR
